import type { Diagnostic } from '@arxic/contracts';

export const ARXIC_SOURCE_UNSUPPORTED_LANGUAGE = 'ARXIC-SOURCE-UNSUPPORTED-LANGUAGE' as const;
export const ARXIC_SOURCE_BINARY_FILE = 'ARXIC-SOURCE-BINARY-FILE' as const;
export const ARXIC_SOURCE_FILE_OVERSIZE = 'ARXIC-SOURCE-FILE-OVERSIZE' as const;
export const ARXIC_SOURCE_PARSE_ERROR = 'ARXIC-SOURCE-PARSE-ERROR' as const;
export const ARXIC_SOURCE_DIRTY_TREE = 'ARXIC-SOURCE-DIRTY-TREE' as const;
export const ARXIC_SOURCE_NO_COMMIT = 'ARXIC-SOURCE-NO-COMMIT' as const;
export const ARXIC_SOURCE_SHALLOW_CLONE = 'ARXIC-SOURCE-SHALLOW-CLONE' as const;
export const ARXIC_SOURCE_REVISION_MISMATCH = 'ARXIC-SOURCE-REVISION-MISMATCH' as const;
export const ARXIC_SOURCE_REPOSITORY_UNAVAILABLE = 'ARXIC-SOURCE-REPOSITORY-UNAVAILABLE' as const;
export const ARXIC_SOURCE_ROUTE_DYNAMIC_REGISTRATION =
  'ARXIC-SOURCE-ROUTE-DYNAMIC-REGISTRATION' as const;
export const ARXIC_SOURCE_HANDLER_UNRESOLVED = 'ARXIC-SOURCE-HANDLER-UNRESOLVED' as const;
export const ARXIC_SOURCE_GRAMMAR_UNAVAILABLE = 'ARXIC-SOURCE-GRAMMAR-UNAVAILABLE' as const;
export const ARXIC_SOURCE_ROUTE_UNSUPPORTED_CONSTRUCT =
  'ARXIC-SOURCE-ROUTE-UNSUPPORTED-CONSTRUCT' as const;
export const ARXIC_SOURCE_ROUTE_FILE_INCLUDE = 'ARXIC-SOURCE-ROUTE-FILE-INCLUDE' as const;

export const SOURCE_DIAGNOSTIC_CODES = [
  ARXIC_SOURCE_UNSUPPORTED_LANGUAGE,
  ARXIC_SOURCE_BINARY_FILE,
  ARXIC_SOURCE_FILE_OVERSIZE,
  ARXIC_SOURCE_PARSE_ERROR,
  ARXIC_SOURCE_DIRTY_TREE,
  ARXIC_SOURCE_NO_COMMIT,
  ARXIC_SOURCE_SHALLOW_CLONE,
  ARXIC_SOURCE_REVISION_MISMATCH,
  ARXIC_SOURCE_REPOSITORY_UNAVAILABLE,
  ARXIC_SOURCE_ROUTE_DYNAMIC_REGISTRATION,
  ARXIC_SOURCE_HANDLER_UNRESOLVED,
  ARXIC_SOURCE_GRAMMAR_UNAVAILABLE,
  ARXIC_SOURCE_ROUTE_UNSUPPORTED_CONSTRUCT,
  ARXIC_SOURCE_ROUTE_FILE_INCLUDE,
] as const;

export type SourceDiagnosticCode = (typeof SOURCE_DIAGNOSTIC_CODES)[number];

export function sourceDiagnostic(
  code: SourceDiagnosticCode,
  subject: string,
  message: string,
): Diagnostic {
  return { code, severity: 'blocked', subject, message };
}
