packages:
  - 'apps/*'
  - 'packages/*'
  - 'test-fixtures/*'
allowBuilds:
  '@ast-grep/cli': true
  better-sqlite3: true
  cpu-features: true
  esbuild: true
  protobufjs: true
  sharp: true
  ssh2: true
  tree-sitter: true
  tree-sitter-javascript: true
  tree-sitter-typescript: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@langchain/core@1.2.4'
  - '@langchain/langgraph@1.4.9'
  - '@crawlee/basic@3.18.0'
  - '@crawlee/browser-pool@3.18.0'
  - '@crawlee/browser@3.18.0'
  - '@crawlee/cheerio@3.18.0'
  - '@crawlee/cli@3.18.0'
  - '@crawlee/core@3.18.0'
  - '@crawlee/http@3.18.0'
  - '@crawlee/jsdom@3.18.0'
  - '@crawlee/linkedom@3.18.0'
  - '@crawlee/memory-storage@3.18.0'
  - '@crawlee/playwright@3.18.0'
  - '@crawlee/puppeteer@3.18.0'
  - '@crawlee/templates@3.18.0'
  - '@crawlee/types@3.18.0'
  - '@crawlee/utils@3.18.0'
  - crawlee@3.18.0
patchedDependencies:
  yazl@3.3.1: patches/yazl@3.3.1.patch
overrides:
  esbuild: 0.28.1
