export const ARXIC_EVIDENCE_REF_INVALID = 'ARXIC-EVIDENCE-REF-INVALID' as const;
export const ARXIC_EVIDENCE_REF_KIND_UNKNOWN = 'ARXIC-EVIDENCE-REF-KIND-UNKNOWN' as const;
export const ARXIC_EVIDENCE_REF_RANGE = 'ARXIC-EVIDENCE-REF-RANGE' as const;
export const ARXIC_SOURCE_REVISION_INVALID = 'ARXIC-SOURCE-REVISION-INVALID' as const;
export const ARXIC_EVIDENCE_ID_GRAMMAR = 'ARXIC-EVIDENCE-ID-GRAMMAR' as const;
export const ARXIC_EVIDENCE_INDEX_INVALID = 'ARXIC-EVIDENCE-INDEX-INVALID' as const;
export const ARXIC_WORKFLOW_INVALID = 'ARXIC-WORKFLOW-INVALID' as const;
export const ARXIC_WORKFLOW_STATUS_UNKNOWN = 'ARXIC-WORKFLOW-STATUS-UNKNOWN' as const;
export const ARXIC_WORKFLOW_TRANSITION_NO_ASSERTIONS =
  'ARXIC-WORKFLOW-TRANSITION-NO-ASSERTIONS' as const;
export const ARXIC_WORKFLOW_NEGATIVE_NO_EXPECTED = 'ARXIC-WORKFLOW-NEGATIVE-NO-EXPECTED' as const;
export const ARXIC_WORKFLOW_VERIFICATION_MISSING = 'ARXIC-WORKFLOW-VERIFICATION-MISSING' as const;
export const ARXIC_WORKFLOW_VERIFIED_WITHOUT_RUNTIME_EVIDENCE =
  'ARXIC-WORKFLOW-VERIFIED-WITHOUT-RUNTIME-EVIDENCE' as const;
export const ARXIC_WORKFLOW_EVIDENCE_ID_INVALID = 'ARXIC-WORKFLOW-EVIDENCE-ID-INVALID' as const;

export type Diagnostic = {
  code: string;
  severity: 'blocked';
  subject: string;
  message: string;
};
