// English singularizer ported from doctrine/inflector 2.1.0 (MIT),
// src/Rules/English/{Inflectible,Uninflected}.php, which is what Laravel's
// Illuminate\Support\Pluralizer::singular() uses to derive resource route
// parameter names (Illuminate/Routing/ResourceRegistrar::getResourceWildcard,
// laravel/framework v13.24.0 src/Illuminate/Routing/ResourceRegistrar.php:615-626).
//
// Rule order, irregular lookup, and the uninflected pattern list mirror the
// upstream ruleset so route URIs generated here match `php artisan route:list`
// for real resource names. Port fidelity is covered by unit tests against
// words drawn from real Laravel applications.

const IRREGULAR_PLURAL_TO_SINGULAR: ReadonlyMap<string, string> = new Map(
  (
    [
      ['abuses', 'abuse'],
      ['algae', 'alga'],
      ['atlases', 'atlas'],
      ['avalanches', 'avalanche'],
      ['axes', 'axis'],
      ['beefs', 'beef'],
      ['blouses', 'blouse'],
      ['brothers', 'brother'],
      ['brownies', 'brownie'],
      ['caches', 'cache'],
      ['cafes', 'cafe'],
      ['canvases', 'canvas'],
      ['caves', 'cave'],
      ['chateaux', 'chateau'],
      ['children', 'child'],
      ['cookies', 'cookie'],
      ['corpuses', 'corpus'],
      ['cows', 'cow'],
      ['criteria', 'criterion'],
      ['curricula', 'curriculum'],
      ['curves', 'curve'],
      ['demos', 'demo'],
      ['dice', 'die'],
      ['dominoes', 'domino'],
      ['echoes', 'echo'],
      ['emphases', 'emphasis'],
      ['epochs', 'epoch'],
      ['foes', 'foe'],
      ['feet', 'foot'],
      ['fungi', 'fungus'],
      ['ganglions', 'ganglion'],
      ['gases', 'gas'],
      ['genies', 'genie'],
      ['genera', 'genus'],
      ['geese', 'goose'],
      ['graffiti', 'graffito'],
      ['graves', 'grave'],
      ['hippopotami', 'hippopotamus'],
      ['hoaxes', 'hoax'],
      ['hoofs', 'hoof'],
      ['humans', 'human'],
      ['irises', 'iris'],
      ['larvae', 'larva'],
      ['leaves', 'leaf'],
      ['lenses', 'lens'],
      ['loaves', 'loaf'],
      ['men', 'man'],
      ['media', 'medium'],
      ['memoranda', 'memorandum'],
      ['monies', 'money'],
      ['mongooses', 'mongoose'],
      ['mottoes', 'motto'],
      ['moves', 'move'],
      ['mythoi', 'mythos'],
      ['neuroses', 'neurosis'],
      ['niches', 'niche'],
      ['niveaux', 'niveau'],
      ['nuclei', 'nucleus'],
      ['numina', 'numen'],
      ['nurseries', 'nursery'],
      ['oases', 'oasis'],
      ['occiputs', 'occiput'],
      ['octopuses', 'octopus'],
      ['opuses', 'opus'],
      ['oxen', 'ox'],
      ['passersby', 'passerby'],
      ['penises', 'penis'],
      ['people', 'person'],
      ['plateaux', 'plateau'],
      ['runners-up', 'runner-up'],
      ['safes', 'safe'],
      ['saves', 'save'],
      ['sexes', 'sex'],
      ['sieves', 'sieve'],
      ['soliloquies', 'soliloquy'],
      ['sons-in-law', 'son-in-law'],
      ['stadiums', 'stadium'],
      ['syllabi', 'syllabus'],
      ['testes', 'testis'],
      ['thieves', 'thief'],
      ['teeth', 'tooth'],
      ['tornadoes', 'tornado'],
      ['trilbys', 'trilby'],
      ['turfs', 'turf'],
      ['valves', 'valve'],
      ['volcanoes', 'volcano'],
      ['waves', 'wave'],
      ['zombies', 'zombie'],
    ] as const
  ).map(([plural, singular]) => [plural, singular] as const),
);

const UNINFLECTED_PATTERNS: readonly RegExp[] = (
  [
    '\\w+media',
    'advice',
    'aircraft',
    'amoyese',
    'art',
    'audio',
    'baggage',
    'bison',
    'borghese',
    'bream',
    'breeches',
    'britches',
    'buffalo',
    'butter',
    'cantus',
    'carp',
    'cattle',
    'chassis',
    'clippers',
    'clothes',
    'clothing',
    'coal',
    'cod',
    'coitus',
    'compensation',
    'congoese',
    'contretemps',
    'coreopsis',
    'corps',
    'cotton',
    'data',
    'debris',
    'deer',
    'diabetes',
    'djinn',
    'education',
    'eland',
    'elk',
    'emoji',
    'equipment',
    'evidence',
    'faroese',
    'feedback',
    'fish',
    'flounder',
    'flour',
    'foochowese',
    'food',
    'furniture',
    'gallows',
    'genevese',
    'genoese',
    'gilbertese',
    'gold',
    'headquarters',
    'herpes',
    'hijinks',
    'homework',
    'hottentotese',
    'impatience',
    'information',
    'innings',
    'jackanapes',
    'jeans',
    'jedi',
    'kin',
    'kiplingese',
    'knowledge',
    'kongoese',
    'leather',
    'love',
    'lucchese',
    'luggage',
    'mackerel',
    'maltese',
    'management',
    'metadata',
    'mews',
    'money',
    'moose',
    'mumps',
    'music',
    'nankingese',
    'news',
    'nexus',
    'niasese',
    'nutrition',
    'offspring',
    'oil',
    'patience',
    'pekingese',
    'piedmontese',
    'pincers',
    'pistoiese',
    'plankton',
    'pliers',
    'pokemon',
    'police',
    'polish',
    'portuguese',
    'proceedings',
    'progress',
    'rabies',
    'rain',
    'research',
    'rhinoceros',
    'rice',
    'salmon',
    'sand',
    'sarawakese',
    'scissors',
    'sea[- ]bass',
    'series',
    'shavese',
    'shears',
    'sheep',
    'siemens',
    'silk',
    'sms',
    'soap',
    'social media',
    'spam',
    'species',
    'staff',
    'sugar',
    'swine',
    'talent',
    'toothpaste',
    'traffic',
    'travel',
    'trousers',
    'trout',
    'tuna',
    'us',
    'vermontese',
    'vinegar',
    'weather',
    'wenchowese',
    'wheat',
    'whiting',
    'wildebeest',
    'wood',
    'wool',
    'yengeese',
    // Uninflected::getSingular() additions beyond the shared defaults:
    '.*ss',
    'fascia',
    'fuchsia',
    'galleria',
    'mafia',
    'militia',
    'pants',
    'petunia',
    'sepia',
    'trivia',
    'utopia',
  ] as const
).map((pattern) => new RegExp(`^${pattern}$`, 'i'));

// Inflectible::getSingular() transformations, in upstream order. Each entry
// maps a pattern to a replacement using $1/$2 capture references.
const SINGULAR_TRANSFORMATIONS: readonly { pattern: RegExp; replacement: string }[] = (
  [
    ['(s)tatuses$', '$1$2tatus'],
    ['(s)tatus$', '$1$2tatus'],
    ['(c)ampus$', '$1$2ampus'],
    ['^(.*)(menu)s$', '$1$2'],
    ['(quiz)zes$', '$1'],
    ['(matr)ices$', '$1ix'],
    ['(vert|ind)ices$', '$1ex'],
    ['^(ox)en', '$1'],
    ['(alias)(es)*$', '$1'],
    ['(buffal|her|potat|tomat|volcan)oes$', '$1o'],
    ['(alumn|bacill|cact|foc|fung|nucle|radi|stimul|syllab|termin|viri?)i$', '$1us'],
    ['([ftw]ax)es', '$1'],
    ['(analys|ax|cris|test|thes)es$', '$1is'],
    ['(shoe|slave)s$', '$1'],
    ['(o)es$', '$1'],
    ['ouses$', 'ouse'],
    ['([^a])uses$', '$1us'],
    ['([m|l])ice$', '$1ouse'],
    ['(x|ch|ss|sh)es$', '$1'],
    ['(m)ovies$', '$1$2ovie'],
    ['(s)eries$', '$1$2eries'],
    ['([^aeiouy]|qu)ies$', '$1y'],
    ['([lr])ves$', '$1f'],
    ['(tive)s$', '$1'],
    ['(hive)s$', '$1'],
    ['(drive)s$', '$1'],
    ['(dive)s$', '$1'],
    ['(olive)s$', '$1'],
    ['([^fo])ves$', '$1fe'],
    ['(^analy)ses$', '$1sis'],
    ['(analy|diagno|^ba|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$', '$1$2sis'],
    ['(tax)a$', '$1on'],
    ['(c)riteria$', '$1riterion'],
    ['([ti])a(?<!regatta)$', '$1um'],
    ['(p)eople$', '$1$2erson'],
    ['(m)en$', '$1an'],
    ['(c)hildren$', '$1$2hild'],
    ['(f)eet$', '$1oot'],
    ['(n)ews$', '$1$2ews'],
    ['eaus$', 'eau'],
    ['^tights$', 'tights'],
    ['^shorts$', 'shorts'],
    ['s$', ''],
  ] as const
).map(([pattern, replacement]) => ({
  pattern: new RegExp(pattern, 'i'),
  replacement,
}));

export function singularize(value: string): string {
  if (value === '') return value;

  const irregular = IRREGULAR_PLURAL_TO_SINGULAR.get(value.toLowerCase());
  if (irregular !== undefined) return matchCase(irregular, value);

  for (const pattern of UNINFLECTED_PATTERNS) {
    if (pattern.test(value)) return value;
  }

  for (const { pattern, replacement } of SINGULAR_TRANSFORMATIONS) {
    if (pattern.test(value)) {
      // PHP preg_replace treats a back-reference to a group that did not
      // participate in the match as an empty string; JavaScript's replace
      // leaves "$2" literal. Expand numeric back-references ourselves.
      const expanded = value.replace(pattern, (...args: unknown[]) => {
        const groups = args
          .slice(0, -2)
          .slice(1)
          .map((group) => (group === undefined ? '' : String(group)));
        return replacement.replace(/\$(\d+)/gu, (_match, digits: string) => {
          const group = groups[Number(digits) - 1];
          return group === undefined ? '' : group;
        });
      });
      return matchCase(expanded, value);
    }
  }

  return value;
}

/** Illuminate\Support\Pluralizer::matchCase — keep the input's capitalization shape. */
function matchCase(output: string, input: string): string {
  if (input === input.toUpperCase()) return output.toUpperCase();
  if (input === input.toLowerCase()) return output.toLowerCase();
  return output;
}
