import type { Workflow } from '@arxic/contracts';

export function generateFixture(workflow: Workflow, approvedOrigins: string[] = []): string {
  void workflow;
  void approvedOrigins;
  return [
    "import { test as base, expect } from '@playwright/test';",
    '',
    'const approvedOrigins = new Set();',
    "const ORIGIN_DENIED = 'ARXIC-COMPILE-ORIGIN-DENIED';",
    'const violations = new WeakMap();',
    '',
    'export const test = base.extend({',
    '});',
    '',
    'export function configureApprovedOrigins(origins) {',
    '  approvedOrigins.clear();',
    '  for (const origin of origins) approvedOrigins.add(origin);',
    '}',
    '',
    'export function assertNetworkContained(context) {',
    '  const denied = violations.get(context)?.denied ?? [];',
    '  if (denied.length > 0) {',
    '    throw new Error(`${ORIGIN_DENIED}: blocked request to unapproved origin ${denied[0]}`);',
    '  }',
    '}',
    '',
    'export async function enforceNetworkContainment(context, operation) {',
    '  const state = violations.get(context);',
    '  if (!state) throw new Error(`${ORIGIN_DENIED}: network policy was not installed`);',
    '  return Promise.race([operation(), state.violation]);',
    '}',
    '',
    'export function assertPageOrigin(page) {',
    '  const pageOrigin = new URL(page.url()).origin;',
    '  if (!approvedOrigins.has(pageOrigin)) {',
    '    throw new Error(`${ORIGIN_DENIED}: blocked navigation to unapproved origin ${pageOrigin}`);',
    '  }',
    '}',
    '',
    'test.beforeEach(async ({ context }) => {',
    '  await context.clearCookies();',
    '  const denied = [];',
    '  let rejectViolation;',
    '  const violation = new Promise((_, reject) => { rejectViolation = reject; });',
    '  violations.set(context, { denied, violation });',
    "  await context.routeWebSocket('**/*', async (webSocket) => {",
    '    const webSocketUrl = new URL(webSocket.url());',
    "    webSocketUrl.protocol = webSocketUrl.protocol === 'ws:' ? 'http:' : 'https:';",
    '    const webSocketOrigin = webSocketUrl.origin;',
    '    if (!approvedOrigins.has(webSocketOrigin)) {',
    '      denied.push(webSocketOrigin);',
    '      rejectViolation(new Error(`${ORIGIN_DENIED}: blocked WebSocket to unapproved origin ${webSocketOrigin}`));',
    "      await webSocket.close({ code: 1008, reason: 'origin denied' });",
    '      return;',
    '    }',
    '    webSocket.connectToServer();',
    '  });',
    "  await context.route('**/*', async (route) => {",
    '    const requestOrigin = new URL(route.request().url()).origin;',
    '    if (!approvedOrigins.has(requestOrigin)) {',
    '      denied.push(requestOrigin);',
    '      rejectViolation(new Error(`${ORIGIN_DENIED}: blocked request to unapproved origin ${requestOrigin}`));',
    "      await route.abort('blockedbyclient');",
    '      return;',
    '    }',
    '    const response = await route.fetch({ maxRedirects: 0 });',
    "    const location = response.headers()['location'];",
    '    if (location) {',
    '      const redirectOrigin = new URL(location, route.request().url()).origin;',
    '      if (!approvedOrigins.has(redirectOrigin)) {',
    '        denied.push(redirectOrigin);',
    '        rejectViolation(new Error(`${ORIGIN_DENIED}: blocked redirect to unapproved origin ${redirectOrigin}`));',
    "        await route.abort('blockedbyclient');",
    '        return;',
    '      }',
    '    }',
    '    try {',
    '      await route.fulfill({ response });',
    '    } catch (error) {',
    "      if (!(error instanceof Error) || !error.message.includes('Route is already handled')) throw error;",
    '    }',
    '  });',
    '});',
    '',
    'test.afterEach(async ({ context }) => {',
    "  await context.unrouteAll({ behavior: 'ignoreErrors' });",
    '  await context.clearCookies();',
    '  assertNetworkContained(context);',
    '});',
    '',
    "test.describe.configure({ mode: 'serial' });",
    'export { expect };',
    '',
  ].join('\n');
}

export function generateConfig(
  workflow: Workflow,
  options: { trace?: 'workflow-policy' | 'off' } = {},
): string {
  const trace =
    options.trace === 'off'
      ? 'off'
      : workflow.verification.trace === 'retain'
        ? 'retain-on-failure'
        : 'off';
  return [
    "import { defineConfig } from '@playwright/test';",
    '',
    'export default defineConfig({',
    "  testDir: './tests',",
    '  workers: 1,',
    "  outputDir: './artifacts/test-results',",
    `  use: { browserName: ${JSON.stringify(workflow.scope.browser)}, headless: true, trace: ${JSON.stringify(trace)}, serviceWorkers: 'block' },`,
    '});',
    '',
  ].join('\n');
}
